### ISSUE TITLE
REPL on WSL takes a solid minute to startup

### ISSUE THREAD

**Issue by ValorZard** [jank-lang/jank#104] opened 2024-10-09 04:40 UTC
these are my specs, for context
![image](https://github.com/user-attachments/assets/2804adba-6aaa-42e4-9228-f55d4823ed13)

**Comment by jeaye** [comment] 2024-10-09 08:17
Hey! More importantly, jank's REPL *does* start on WSL. That's cool. I think you're the first to get it running there.

On my Linux machine, that it takes 12 seconds to start. It's taking a long time because it's JIT compiling around 80k lines of C++ code, for clojure.core. If you're working on #85 and want a faster startup time, you can comment out this line: https://github.com/jank-lang/jank/blob/main/compiler%2Bruntime/src/cpp/main.cpp#L117

I'm working on this general problem right now, as part of #100, so I'll close this ticket as a dupe of that. Once we're generating LLVM IR and loading that up, performance will be significantly better. Turns out JIT compiling 80k lines of C++ is very slow. :joy:

**Closed by jeaye** 2024-10-09 08:17 UTC
